export const SYSTEM_SOUNDS: Set<string> = new Set([
  'BUZZ_PRESSED',
  'BUZZ_LOCKED',
  'BUZZ_INVALIDATED',
  'CORRECT_ANSWER',
  'WRONG_ANSWER',
  'TIMER_END',
  'GAME_START',
  'GAME_END',
  'WAITING',
  'SUSPENSE',
]);
